### ISSUE TITLE
overriding default matches doesn't work

### ISSUE THREAD

**Issue by dbarrosop** [KaraMCC/vim-gemini#2]
Hello,
first of all, thanks for the plugin, it's simple and works wonders :)

I have been trying to override the default matches as instructed in the README but it doesn't work. I think the plugin is overriding the user setting. I made a slight change:

``` diff
diff --git a/plugin/gemini.vim b/plugin/gemini.vim
index ee8c58b..dde44aa 100644
--- a/plugin/gemini.vim
+++ b/plugin/gemini.vim
@@ -4,7 +4,7 @@ endif
 let g:loaded_gemini_plugin = 1

 " Define default matches
-let g:gemini#default_matches = {
+let g:gemini#default_matches_included = {
             \'.*': [['(', ')'], ['{', '}'], ['[', ']'], ['"', '"']],
             \'.*python\|.*php\|.*c\|.*cpp\|.*cs\|.*sh\|.*html\|.*xml\|.*vim\|.*perl\|.*rust\|.*java\|.*javascript': [["'", "'"]],
             \'.*html\|xml': [['<', '>']],
@@ -14,6 +14,7 @@ let g:gemini#default_matches = {
 let g:gemini#match_list = get(g:, 'gemini#match_list', {})
 let g:gemini#match_in_comment = get(g:, 'gemini#match_in_comment', 0)
 let g:gemini#cozy_matching = get(g:, 'gemini#cozy_matching', 1)
+let g:gemini#default_matches = get(g:,'gemini#user_default_matches', g:gemini#default_matches_included)
```

which allowed me to override the option via `g:gemini#user_default_matches`. I can open a PR but figured I'd ask first in case I was doing something wrong.

**Comment by lighthouse-4u** [comment]
Thanks for pointing out this problem. The plugin was previously bugged and would overwrite the user's custom matches with the default ones no matter what.

The new version of the plugin includes a change which should fix the problem.
